cmake_minimum_required(VERSION 3.20)
project(lsh_steam_stats_reader LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(GODOTCPP_BUILD_PROFILE "${CMAKE_CURRENT_SOURCE_DIR}/build_profile.json" CACHE PATH "" FORCE)
set(GODOTCPP_USE_STATIC_CPP ON CACHE BOOL "" FORCE)
add_subdirectory("${GODOT_CPP_SOURCE}" godot-cpp)
add_library(steam_stats_reader SHARED extension.cpp)
target_link_libraries(steam_stats_reader PRIVATE godot-cpp::template_release)
target_compile_options(steam_stats_reader PRIVATE /W4 /WX /Brepro /guard:cf)
target_link_options(steam_stats_reader PRIVATE /Brepro /DYNAMICBASE /NXCOMPAT)
