"""Source/inverse and arithmetic checks only; never a GDScript/runtime pass."""
import ast
import hashlib
import json
from pathlib import Path
import sys

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent
namespace = {'__file__':str(HERE/'prepare.py'),'__name__':'unit_sections_static_prepare'}
exec(compile((HERE/'prepare.py').read_text(encoding='utf-8'),str(HERE/'prepare.py'),'exec'),namespace)

def main():
    checks=[]
    def check(value,label):
        if not value: raise RuntimeError(label)
        checks.append(label)
    for name in ['prepare.py','static_checks.py']:
        ast.parse((HERE/name).read_text(encoding='utf-8')); check(True,name+' Python AST')
    pins=json.loads((HERE/'pins.json').read_text(encoding='utf-8'))
    source=Path(pins['source_contract']['scripts/unit.gd']['frozen_path']).read_bytes()
    for label,raw in [('raw',source),('lf',namespace['lf'](source))]:
        output,proof,restored=namespace['transform'](raw)
        check(restored==raw,label+' inverse restores every input byte')
        check(output==(HERE/'generated'/('unit_instrumented.'+label+'.gd.txt')).read_bytes(),label+' generated bytes reproduce')
        check(proof['outer_returns_by_section']==[5,0,3,0],label+' all eight original outer returns preserved')
        check(proof['one_original_call_in_wrapper'],label+' exactly one complete original call per wrapper')
        check(proof['original_outer_physics_process_unchanged'],label+' native _physics_process byte-identical')
    for label,bad in [('changed source',source+b'\n'),('already instrumented',output)]:
        rejected=False
        try: namespace['transform'](bad)
        except RuntimeError: rejected=True
        check(rejected,label+' rejected before transform')
    for name,expected in pins['generated_sha256'].items():
        check(hashlib.sha256((HERE/'generated'/name).read_bytes()).hexdigest()==expected,'artifact pin '+name)
    check(pins['m1_driver']['inverse_restores_exact_m1_run'],'all original M1 _run bytes retained after removing five hooks')
    ledger=(HERE/'ledger.gd.in').read_text(encoding='utf-8')
    hot=ledger[ledger.index('static func begin_body('):ledger.index('static func begin_measurement(')]
    check(all(token not in hot for token in ['.new(','.resize(','.append(','.duplicate(','.keys()']), 'body/step hot ledger does not allocate objects or dynamic per-unit rows')
    check('not in [' not in hot and 'in range(' not in hot,'hot guard/step loops do not build literal membership/range arrays')
    check(all(token not in ledger for token in ['randf(','randi(','randf_range(','seed(','randomize(']),'ledger adds no RNG')
    check('if timed else -1' in ledger and 'clockless_costs' in ledger,'clockless timing unavailable, never reported as zero')
    check('body_total_us - partition' in ledger and 'body_starts != body_completions' in ledger,'runtime completion and exact partition checks present')
    check('depth != 1' in ledger and 'token < 0' in ledger,'unexpected nested body marks diagnostic invalid without skipping original body')
    # Pure arithmetic examples, not a mirror of the Unit or actual GDScript QA.
    trajectories=[(100,[],128),(100,[104,119],140),(100,[105,123,156],190)]
    for start,cuts,end in trajectories:
        points=[start]+cuts+[end]
        check(sum(b-a for a,b in zip(points,points[1:]))==end-start,'same-clock telescoping for last section '+str(len(cuts)))
    reaches=[3,2,2,1]; exits=[1,0,1,1]
    check(all(reaches[i]-reaches[i+1]==exits[i] for i in range(3)) and reaches[3]==exits[3],'aggregate early/normal exit conservation fixture')
    need_fields=['godot_run','gdscript_parsed_or_executed','mirror_created','production_mutated']
    receipt=json.loads((HERE/'preparation_receipt.json').read_text(encoding='utf-8'))
    check(all(receipt[x] is False for x in need_fields),'preparation cannot imply engine/mirror/production execution')
    result={'passed':True,'checks':checks,'check_count':len(checks),'source_inverse_only':True,
            'gdscript_parsed_or_executed':False,'godot_run':False,'mirror_created':False,'production_mutated':False,
            'performance_claim':False,'limitations':'Arithmetic examples verify only partition equations; all actual return paths and semantics still require reviewed source and real engine execution.'}
    namespace['save'](HERE/'static_receipt.json',result)
    print(json.dumps({'passed':True,'checks':len(checks),'godot_run':False,'gdscript_parsed_or_executed':False}))

if __name__=='__main__': main()
