"""Source-level checks and offline ledger fixtures. Does not run/parse GDScript."""
import copy
import json
from pathlib import Path
import sys

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent


def module(name):
    path = HERE / (name + ".py")
    namespace = {"__file__": str(path), "__name__": "physics_step_static_" + name}
    exec(compile(path.read_text(encoding="utf-8"), str(path), "exec"), namespace)
    return namespace


def main():
    runner = module("prepare_and_run")
    analyzer = module("analyze")
    checks = []
    def check(value, label):
        if not value: raise RuntimeError(label)
        checks.append(label)
    pins = json.loads((HERE / "pins.json").read_text(encoding="utf-8"))
    for path in runner["OWNED"]:
        kind = Path(path).stem
        original = (HERE / "frozen" / (kind + "_original.bin")).read_bytes()
        before, end = runner["span"](original, "_physics_process")
        original_function = original[before:end]
        changed, proof = runner["instrument"](original, kind)
        check(changed == (HERE / "generated" / (kind + "_instrumented.gd.txt")).read_bytes(), kind + " generated bytes reproduce")
        check(runner["sha"](original) == pins["originals"][path]["raw_sha256"], kind + " original SHA pinned")
        private = original_function.replace(b"func _physics_process(", b"func " + runner["ORIGINAL_NAME"].encode() + b"(", 1)
        check(changed.count(private) == 1, kind + " full original callback body occurs once")
        check(proof["original_call_sites_in_wrapper"] == 1, kind + " wrapper calls original exactly once")
        check(private.count(b"return") == original_function.count(b"return"), kind + " original early-return tokens retained")
        check(private.count(b"\n") == original_function.count(b"\n"), kind + " original body line structure retained")
    # Two physics ticks caught up in frame 0, zero in frame 1, eight in frame 2.
    step_columns = ["engine_physics_frame", "start_us", "last_measured_callback_end_us", "battle_callback_us", "unit_callbacks_us", "battle_callback_count", "unit_callback_count", "engine_process_frame_at_tick", "presentation_index"]
    frame_columns = ["start_us", "end_us", "engine_process_frame", "engine_physics_frame", "first_step_index", "physics_step_count", "engine_frames_drawn", "presentation_bookkeeping_us_partial"]
    steps = [[400, 1000, 8000, 2000, 4000, 1, 206, 100, 0], [401, 9000, 16000, 2000, 4000, 1, 206, 100, 0]]
    for i in range(8): steps.append([402 + i, 41000 + i * 13000, 52000 + i * 13000, 4000, 6000, 1, 206, 102, 2])
    frames = [[0, 20000, 100, 401, 0, 2, 100, 4], [20000, 40000, 101, 401, 2, 0, 101, 4], [40000, 150000, 102, 409, 2, 8, 102, 4]]
    fixture = {"mode": "timed", "timing_available": True, "step_columns": step_columns, "frame_columns": frame_columns,
               "step_rows": steps, "frame_rows": frames, "physics_ticks": 10, "diagnostic_valid": True}
    result = analyzer["summarize"](fixture)
    check(result["analysis_valid"], "2/0/8 physics steps per presentation group accepted")
    check(result["slow_presentations_median_physics_steps"] == 8, "slow-frame catch-up count derived from actual grouped ticks")
    check(result["first_window_battle_callback_us"] == 36000 and result["first_window_unit_callbacks_us"] == 56000, "separate callback totals summed once")
    check(result["per_presentation"][1]["measured_disjoint_callbacks_us"] == 0, "zero-physics frame contributes no callbacks")
    control = copy.deepcopy(fixture); control.update(mode="clockless_control", timing_available=False)
    for row in control["step_rows"]:
        for index in (2, 3, 4, 5, 6): row[index] = -1
    result = analyzer["summarize"](control)
    check(result["analysis_valid"] and result["first_window_battle_callback_us"] is None, "clockless control retains unavailable costs, not zero")
    wrong = copy.deepcopy(fixture); wrong["step_rows"][3][8] = 1
    check(not analyzer["summarize"](wrong)["analysis_valid"], "incorrect presentation ownership rejected")
    wrong = copy.deepcopy(fixture); wrong["step_rows"][1][0] = 999
    check(not analyzer["summarize"](wrong)["analysis_valid"], "nonconsecutive Engine physics frame rejected")
    wrong = copy.deepcopy(fixture); wrong["frame_rows"][2][4] = 1
    check(not analyzer["summarize"](wrong)["analysis_valid"], "duplicate/missing step ownership rejected")
    wrong = copy.deepcopy(fixture); wrong["step_rows"][0][3] = 999999
    check(not analyzer["summarize"](wrong)["analysis_valid"], "overlapping/impossible callback budget rejected")
    wrong = copy.deepcopy(fixture); wrong["overflow"] = True
    check(not analyzer["summarize"](wrong)["analysis_valid"], "overflow rejects diagnostic integrity")
    text = (HERE / "ledger.gd.in").read_text(encoding="utf-8")
    check("resize(" not in text[text.index("static func start("):text.index("static func export_rows(")], "no buffer resizing in measured loop")
    check("append(" not in text[text.index("static func start("):text.index("static func export_rows(")], "no array appends in measured ledger loop")
    check(all(token not in text for token in ("randf(", "randi(", "seed(", ".new(")), "ledger adds no RNG calls or Object instances")
    driver = (HERE / "driver.gd.in").read_text(encoding="utf-8")
    check('extends "res://tools/polish_performance_probe.gd"' in driver and "func _new_battle" not in driver and "func _on_tick" not in driver, "exact M1 fixture and tick observer inherited")
    receipt = {"checks": len(checks), "passed": checks, "godot_run": False, "git_run": False,
               "gdscript_parsed_or_executed": False, "production_mutated": False, "performance_claim": False}
    (HERE / "static_checks_receipt.json").write_bytes((json.dumps(receipt, indent=2) + "\n").encode())
    print(json.dumps({"checks": len(checks), "gdscript_validated": False, "performance_claim": False}))


if __name__ == "__main__":
    main()
